# run a postgres server

version: '3.1'
services:

  pg:
    image:               postgres:10-alpine
    ports:               ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: example
    networks:            [main]


networks:
  main:
